fixed vuln

diff --git a/.github/workflows/validate-prs.yaml b/.github/workflows/validate-prs.yaml
--- a/.github/workflows/validate-prs.yaml
+++ b/.github/workflows/validate-prs.yaml
@@ -12,6 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       ERROR_MSG: "The PR title does not match the required format: <type>(<scope>): <title>"
+      PR_TITLE: ${{ github.event.pull_request.title }}
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
@@ -22,7 +23,7 @@ jobs:
           .github/pr-title-types.yaml
           .github/scripts/pr-issue-info/title-fail.md
     - name: Print PR Title
-      run: echo "${{ github.event.pull_request.title }}"
+      run: echo "$PR_TITLE"
     - name: Set up Python 
       uses: actions/setup-python@v4
       with:
@@ -35,8 +36,7 @@ jobs:
       run: |
         regex=$(python3 .github/scripts/pr-issue-info/get_title_types.py)
         echo "Title regex: $regex"
-        title="${{ github.event.pull_request.title }}"
-        echo "$title" | grep -Pq "$regex" || (echo "$ERROR_MSG" && echo "TITLE_CHECK_FAILED=true" >> $GITHUB_ENV)
+        echo "$PR_TITLE" | grep -Pq "$regex" || (echo "$ERROR_MSG" && echo "TITLE_CHECK_FAILED=true" >> $GITHUB_ENV)
     - name: Check for comment tag
       if: env.TITLE_CHECK_FAILED != 'true'
       run: |
@@ -75,6 +75,7 @@ jobs:
     env:
       BODY: ${{ github.event.pull_request.body }}
       LABELS: ${{ toJson(github.event.pull_request.labels) }}
+      PR_TITLE: ${{ github.event.pull_request.title }}
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
@@ -87,8 +88,6 @@ jobs:
       run: echo "USERNAME=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
     - name: Install JQ
       run: sudo apt-get install jq
-    - name: Get title
-      run: echo "TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
     - name: Check user username
       run: |
         response=$(curl -s -H "Authorization: token ${{ secrets.KICS_BOT_PAT }}" "https://api.github.com/orgs/Checkmarx/teams/kics-core-team/members")
@@ -108,7 +107,7 @@ jobs:
         fi
     - name: Add feature or feature request label
       run: |
-        if [[ "$TITLE" == feat* ]]; then
+        if [[ "$PR_TITLE" == feat* ]]; then
           if [[ "$IS_MEMBER" == "true" ]]; then
             echo "Adding 'feature' label..."
             curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -d '{"labels": ["feature"]}'
@@ -127,7 +126,7 @@ jobs:
         fi
     - name: Add documentation label
       run: |
-        if [[ "$TITLE" == docs* ]]; then
+        if [[ "$PR_TITLE" == docs* ]]; then
           echo "Adding 'documentation' label..." 
           curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -d '{"labels": ["documentation"]}'
         else
@@ -138,7 +137,7 @@ jobs:
         fi
     - name: Add bug label
       run: |
-        if echo "$TITLE $BODY" | grep -iqP "(\\b|_)bugs?(\\b|_)"; then
+        if echo "$PR_TITLE $BODY" | grep -iqP "(\\b|_)bugs?(\\b|_)"; then
           echo "Adding 'bug' label..."
           curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -d '{"labels": ["bug"]}'
         else
@@ -149,7 +148,7 @@ jobs:
         fi
     - name: Add query label
       run: |
-        if echo "$TITLE $BODY" | grep -iqP "(\\b|_)quer(y|ies)(\\b|_)"; then
+        if echo "$PR_TITLE $BODY" | grep -iqP "(\\b|_)quer(y|ies)(\\b|_)"; then
           echo "Adding 'query' label..."
           curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels -d '{"labels": ["query"]}'
         else
@@ -171,7 +170,7 @@ jobs:
         declare -p keywords
         declare -a labels_to_add=()
         for keyword in "${!keywords[@]}"; do
-          if echo "$TITLE $BODY" | grep -iPq "(\\b|_)$keyword(\\b|_)"; then
+          if echo "$PR_TITLE $BODY" | grep -iPq "(\\b|_)$keyword(\\b|_)"; then
             labels_to_add+=("${keywords[$keyword]}")
           fi
         done
