changed script

diff --git a/.github/workflows/validate-issues.yaml b/.github/workflows/validate-issues.yaml
--- a/.github/workflows/validate-issues.yaml
+++ b/.github/workflows/validate-issues.yaml
@@ -1,9 +1,37 @@
-name: add-issues-labels
+name: validate-issues
 on:
   issues:
     types: [opened, edited, reopened]
-
 jobs:
+  title-check:
+    permissions:
+        pull-requests: write
+    runs-on: ubuntu-latest
+    env:
+      BODY: ${{ github.event.issue.body }}
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        persist-credentials: false
+        sparse-checkout: |
+          .github/scripts/pr-issue-info/issue-fail.md
+          .github/scripts/pr-issue-info/get_title_types.py
+          .github/issue-title-types.yaml
+    - name: Check issue title 
+      env:
+        FILE_PATH: .github/issue-title-types.yaml
+      run: |
+        regex=$(python3 .github/scripts/pr-issue-info/get_title_types.py)
+        echo "Title regex: $regex"
+        title="${{ github.event.pull_request.title }}"
+        echo "$title" | grep -Pq "$regex" || (echo "$ERROR_MSG" && echo "TITLE_CHECK_FAILED=true" >> $GITHUB_ENV)
+   
+    - name: Add comment
+      if: env.TITLE_CHECK_FAILED == 'true'
+    - name: Fail the workflow
+      if: env.TITLE_CHECK_FAILED == 'true'
+      run: exit 1
   labels-check:
     runs-on: ubuntu-latest
     env:
